controllers:
    resource: ../../src/Controller/
    type: annotation

crud_controllers:
    resource: ../../src/Controller/CRUD/
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
